pull_request_rules:

  - name: Add CI label
    conditions:
      - or:
          - "title~=^tox:"
          - "title~=^ci:"
          - "files~=tox.ini"
          - "files~=tests"
    actions:
      label:
        add:
          - ci

  - name: Add Mergify label
    conditions:
      - or:
          - "title~=^mergify:"
          - "files~=.mergify.yml$"
    actions:
      label:
        add:
          - mergify

  - name: Add Documentation label
    conditions:
      - or:
          - "title~=^docs:"
          - "files~=docs"
          - "files~=.rst$"
    actions:
      label:
        add:
          - documentation

  - name: Automatic merge on approval
    conditions:
      - and:
        - "check-success=style (docs)"
        - "check-success=style (style)"
        - "check-success=style (pkglint)"
        - "check-success=Test macOS (3.8)"
        - "check-success=Test macOS (3.9)"
        - "check-success=Test macOS (3.10)"
        - "check-success=Test macOS (3.11)"
        - "check-success=Test Ubuntu (3.8)"
        - "check-success=Test Ubuntu (3.9)"
        - "check-success=Test Ubuntu (3.10)"
        - "check-success=Test Ubuntu (3.11)"
        - "check-success=Test Zsh"
        - "-draft"
        - "#approved-reviews-by>=1"
    actions:
      merge:
        method: merge
